### ISSUE TITLE
Upgrade breaks DSSVue Script Editor

### ISSUE THREAD

**Issue by jprine** [EnviroCentre/jython-upgrade#1]
After applying the upgrade, when you try to save files from the Script Editor in HEC-DSSVue, you get the following error:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.python.core.__builtin__.compile(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/python/core/PyCode;
    at hec.script.ScriptEngine.compile(ScriptEngine.java:246)
    at hec.script.AbstractScriptEditor.saveScript(AbstractScriptEditor.java:1938)
    at hec.script.AbstractScriptEditor$5.buttonCmdActionPerformed(AbstractScriptEditor.java:1058)
    at rma.awt.ButtonCmdPanel.fireActionPerformed(ButtonCmdPanel.java:278)
    at rma.awt.ButtonCmdPanel.actionPerformed(ButtonCmdPanel.java:223)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

To reproduce:
1. Install the Jython update.
2. Open the console output.
3. Go to `Tools->Script Editor`
4. Double-click a script to edit.
5. Hit either the `Save and Test` or `Save` buttons. 

Result: File fails to save and issues the above warning.

**Comment by faph** [comment]
Ah, so far I was pleasantly surprised that upgrading java and jython didn't cause any issues. It seems from the error above that DDSVue pre-compiles the scripts using the jython method `org.python.core.__builtin__.compile()`. This method has probably been removed in jython 2.7.

I don't think there is much we can do about this, as this is built in DDSVue. As you say, the built-in editor is probably best to be avoided!

**Comment by jprine** [comment]
That's a bugger... 
The really annoying thing is that it seems that DSSVue only loads or reads the scripts when it starts up or when save is pressed in the editor.  This means that when I make changes to a script I'm working on, I need to re-start DSSVue to get it to work.  At least with the script editor you can quickly fix a minor bug without a restart. Is there any way around restarting every time?

**Comment by faph** [comment]
Yes, that's what I've been noticing as well. In the past, I've tried deleting the compiled files cache, but I don't think that worked either. If we somehow can figure out exactly how DSSVue is loading the files at startup we may be able to trigger a recompile + reload.
